### ISSUE TITLE
menu programs lost on side by side

### ISSUE THREAD

**Issue by sz3bbyla** [ramensoftware/windows-11-start-menu-styling-guide#110]
Windows 11 Start Menu Styler
after installing all been ok work great seting on sidebyside
after an restart the menu programs in the rigth side just dispear, with an emty space instead of programs
I change to sidebyside2 , all working great
turning back to sidebyside the same problem, list of programs emty space
I dezinstall an reinstall again but with the same problem
I don't know where are stored files for mods maibe I can just delete that files and reinstall again

**Comment by m417z** [comment]
Since it looks like a problem with the theme and not with the mod, moved to windows-11-start-menu-styling-guide.

What's your Windows 11 version? Can you post a screenshot?

**Comment by EnderMinecraft** [comment]
i'm also having this problem for both sidebyside and sidebyside2
my windows 11 version is 27749.1000
![Screenshot 2024-11-17 190049](https://github.com/user-attachments/assets/94934659-e840-403e-a09f-6d647b701fbf)

**Comment by m417z** [comment]
@EnderMinecraft you're using a preview build. Preview builds (Dev, Canary, Beta, Release Preview) aren't generally supported. They're a moving target, some things might work, and other things might be incompatible. For best compatibility with Windhawk, avoid using preview Windows builds.

**Comment by Jedson3614** [comment]
On some level I can understand you not supporting preview builds, but what really has changed in the start menu on any build that would make your mod or themes cause the folder access to disappear. That in it's self doesn't make sense, because if it did you would have had it fixed by now. What margin would have changed from one build to the next? I'm guessing somewhere in your code it's missing something or the margins are just way off to suite most people for a specific build. Windows doesn't come with an update and say, hey why don't we change the start menu margins. 

Where in your code can I find the start menu margins? If you point me tot hat I may be able to at least fix mine!

**Comment by Jedson3614** [comment]
On some level I can understand you not supporting preview builds, but what really has changed in the start menu on any build that would make your mod or themes cause the folder access to disappear. That in it's self doesn't make sense, because if it did you would have had it fixed by now. What margin would have changed from one build to the next? I'm guessing somewhere in your code it's missing something or the margins are just way off to suite most people for a specific build. Windows doesn't come with an update and say, hey why don't we change the start menu margins.

**Comment by Jedson3614** [comment]
On some level I can understand you not supporting preview builds, but what really has changed in the start menu on any build tyhat would make your mod or themes cause the folder access to disappear. That in it's self doesn't make sense, because if it did you would have had it fixed by now. What margin would have changed from one build to the next? I'm guessing somewhere in your code it's missing something or the margins are just way off to suite most people for a specific build. Windows doesn't come with an update and say, hey why don't we change the start menu margins.

**Comment by m417z** [comment]
@Jedson3614 I don't know what changed. If you'd like to try and get it fixed, you can import the theme manually by following the instructions here:
https://github.com/ramensoftware/windows-11-start-menu-styling-guide/blob/main/Themes/SideBySide/README.md
Then you can go to the mod settings and play with the styles to find out which style causes the problem, and then to find out how to fix it.

**Comment by EnderMinecraft** [comment]
![Screenshot 2025-01-04 173349](https://github.com/user-attachments/assets/6c0f8b34-764a-4e87-86f4-a0294c1be63e)
Seem like the recent Windows build hardcoded the startmenu size. It is now cutted off when I tried to change size of the start menu

**Comment by EnderMinecraft** [comment]
update: by disable 48697323 and 48433719 using vivetool, the app list work again:D.but it still get cutted off tho
![Screenshot (1)](https://github.com/user-attachments/assets/4f77f611-7491-4be5-890c-cf1a113ac78b)
