### ISSUE TITLE
Rosepine Issue And Inquery

### ISSUE THREAD

**Issue by NearRaindrop116** [ramensoftware/windows-11-start-menu-styling-guide#172]
With the rosepine theme the start menu works great however the search menu does not apply the theme, i tried including SearchHost.exe in the advanced tab and that didnt work either.

https://github.com/user-attachments/assets/126026a3-8e3a-449a-9d0d-e4360626db26

I also want to know if its possible to change the color of the outline on the rosepine menu as i couldnt find it anywhere and would like to

**Comment by NearRaindrop116** [comment]
I figured out how to change the outline of it now i just need help with the search menu not working

**Comment by bbmaster123** [comment]
@NearRaindrop116 you shouldn't need to specifically include searchhost.exe in the advanced tab anymore. Can you confirm:

1. you didn't add searchhost.exe to the exclude list by mistake? I've done that before!
2. there are no forked start menu styler mods which may also be trying to apply styles to search at the same time?
3. you are not using a preview version of windows, especially insider builds?

**Comment by bbmaster123** [comment]
> I dont know what an insider version is so probably not

If you've never heard of it then yes, its unlikely you are on an insider version which you have to specifically enroll yourself in. You may still be on a non insider preview though, go to start, type winver and hit enter, and tell me what it says next to OS build in the brackets. Mine says 26100.3476. 

> Unless the exclusion list is the one on top then no

ok so then we can ignore this one :)
the way it should be configured generally, is both include/exclude boxes blank, toggle at the very bottom turned off

> I have not forked anything I'm using the one by the m-something guy

okay thanks for confirming.
I think you're referring to Michael (M417z), he's the creator of Windhawk and many of the mods :)
also just a great guy all around!

Have you tried manually killing/restarting searchhost.exe in task manager? Any other search related mods enabled at the moment?

**Comment by NearRaindrop116** [comment]
@bbmaster123 
Microsoft Windows
Version 24H2 (OS Build 26100.2314)

I havent updated in a bit, that might be the problem. however i did navigate to the folder with searches file in it via task manager and its called FESearchHost.exe and not SearchHost.exe

![Image](https://github.com/user-attachments/assets/f79d1dbb-afdf-49bd-887d-093489bafed5)

![Image](https://github.com/user-attachments/assets/302aaf56-d134-4299-811b-0d50996d3927)
Should i try adding this to the inclusion list and see if that works?

**Comment by bbmaster123** [comment]
@NearRaindrop116 
I double checked, and `Version 24H2 (OS Build 26100.2314)` is a stable build of windows from around november

you should have both files. Search wouldn't work without SearchHost.exe at all, and FESearchHost.exe seems to be a sub process, possibly meant for the search at the top right in file explorer. 

Which other custom styles have you added? I see in the video that your search menu is being styled, since it has the outline around its search bar, or are you trying to change the contents within search (not background color or outline)? Could you send your full style code?

If adding custom styles, make sure everything not related to the search's main content is above the webview styles section, see [here](https://github.com/ramensoftware/windows-11-start-menu-styling-guide?tab=readme-ov-file#search-menu-webview-styles) for more on that

**Comment by NearRaindrop116** [comment]
@bbmaster123 

{"controlStyles[0].target":"Windows.UI.Xaml.Controls.Grid#UndockedRoot","controlStyles[0].styles[0]":"Width=350","controlStyles[0].styles[1]":"Margin=0,-40,0,0","controlStyles[1].target":"Windows.UI.Xaml.Controls.Grid#AllAppsRoot","controlStyles[1].styles[0]":"Width=320","controlStyles[1].styles[1]":"Transform3D:=<CompositeTransform3D TranslateX=\"-800\" />","controlStyles[1].styles[2]":"Margin=-30,-60,0,0","controlStyles[2].target":"Windows.UI.Xaml.Controls.Grid#ShowMoreSuggestions","controlStyles[2].styles[0]":"Visibility=Collapsed","controlStyles[3].target":"Windows.UI.Xaml.Controls.Grid#SuggestionsParentContainer","controlStyles[3].styles[0]":"Visibility=Collapsed","controlStyles[4].target":"Windows.UI.Xaml.Controls.Grid#TopLevelSuggestionsListHeader","controlStyles[4].styles[0]":"Visibility=Collapsed","controlStyles[5].target":"StartDocked.SearchBoxToggleButton","controlStyles[5].styles[0]":"Margin=114,53,114,0","controlStyles[5].styles[1]":"Background=#1f1d2e","controlStyles[5].styles[2]":"BorderThickness=0","controlStyles[6].target":"Windows.UI.Xaml.Controls.Grid#TopLevelRoot > Windows.UI.Xaml.Controls.Border","controlStyles[6].styles[0]":"Visibility=Collapsed","controlStyles[7].target":"Windows.UI.Xaml.Controls.Button#CloseAllAppsButton","controlStyles[7].styles[0]":"Visibility=Collapsed","controlStyles[8].target":"StartMenu.PinnedList","controlStyles[8].styles[0]":"Height=340","controlStyles[9].target":"StartDocked.NavigationPaneView#Margin","controlStyles[9].styles[0]":"Margin=210,0,210,0","controlStyles[10].target":"Windows.UI.Xaml.Controls.Border#AcrylicBorder","controlStyles[10].styles[0]":"BorderThickness=1.5","controlStyles[10].styles[1]":"CornerRadius=25","controlStyles[10].styles[2]":"BorderBrush=#230752","controlStyles[10].styles[3]":"Background=#191724","controlStyles[11].target":"StartDocked.StartSizingFramePanel","controlStyles[11].styles[0]":"CornerRadius=25","controlStyles[12].target":"Windows.UI.Xaml.Controls.FontIcon > Windows.UI.Xaml.Controls.Grid > Windows.UI.Xaml.Controls.TextBlock","controlStyles[12].styles[0]":"Foreground=#eb6f92","controlStyles[13].target":"Windows.UI.Xaml.Controls.TextBlock#AppDisplayName","controlStyles[13].styles[0]":"Foreground=#e0def4","controlStyles[14].target":"Windows.UI.Xaml.Controls.TextBlock#DisplayName","controlStyles[14].styles[0]":"Visibility=Collapsed","controlStyles[15].target":"Windows.UI.Xaml.Controls.TextBlock#PinnedListHeaderText","controlStyles[15].styles[0]":"Visibility=Collapsed","controlStyles[16].target":"Windows.UI.Xaml.Controls.TextBlock#AllAppsHeading","controlStyles[16].styles[0]":"Visibility=Collapsed","controlStyles[17].target":"StartDocked.StartSizingFrame","controlStyles[17].styles[0]":"MaxHeight=580","controlStyles[18].target":"Windows.UI.Xaml.Controls.Grid#UserTileIcon","controlStyles[18].styles[0]":"Visibility=Collapsed","controlStyles[19].target":"Windows.UI.Xaml.Controls.Border#AcrylicOverlay","controlStyles[19].styles[0]":"Opacity=0","controlStyles[20].target":"StartMenu.PinnedListTile > Windows.UI.Xaml.Controls.Grid#Root","controlStyles[20].styles[0]":"Padding=0,25,0,0","controlStyles[21].target":"Windows.UI.Xaml.Controls.Grid#DroppedFlickerWorkaroundWrapper > Windows.UI.Xaml.Controls.Border#BackgroundBorder","controlStyles[21].styles[0]":"BorderBrush=#191724","controlStyles[21].styles[1]":"BorderThickness=5","controlStyles[21].styles[2]":"Background=#1f1d2e","controlStyles[21].styles[3]":"CornerRadius=20","controlStyles[22].target":"StartDocked.PowerOptionsView","controlStyles[22].styles[0]":"Margin=-260,0,0,0","controlStyles[23].target":"StartDocked.NavigationPaneButton#PowerButton > Windows.UI.Xaml.Controls.Grid > Windows.UI.Xaml.Controls.Border#BackgroundBorder","controlStyles[23].styles[0]":"Background=#1f1d2e","controlStyles[23].styles[1]":"CornerRadius=20","controlStyles[24].target":"Windows.UI.Xaml.Controls.TextBlock[Text=]","controlStyles[24].styles[0]":"Text=      ","controlStyles[25].target":"StartDocked.NavigationPaneButton#PowerButton","controlStyles[25].styles[0]":"Width=120","controlStyles[26].target":"Windows.UI.Xaml.Controls.Grid#InnerContent > Windows.UI.Xaml.Shapes.Rectangle","controlStyles[26].styles[0]":"Margin=150,53,134,0","controlStyles[27].target":"Windows.UI.Xaml.Controls.TextBlock#PlaceholderText","controlStyles[27].styles[0]":"Text=Search","controlStyles[27].styles[1]":"Foreground=#524f67","controlStyles[27].styles[2]":"FontFamily=JetBrainsMono NF","controlStyles[28].target":"Windows.UI.Xaml.Controls.TextBlock[Text=]","controlStyles[28].styles[0]":"Foreground=#c4a7e7","controlStyles[29].target":"StartDocked.UserTileView","controlStyles[29].styles[0]":"Visibility=Collapsed","controlStyles[30].target":"Windows.UI.Xaml.Controls.Grid#ContentBorder > Windows.UI.Xaml.Controls.Border#BackgroundBorder","controlStyles[30].styles[0]":"Background=#1f1d2e","controlStyles[30].styles[1]":"CornerRadius=20","controlStyles[31].target":"Windows.UI.Xaml.Controls.TextBlock[Text=]","controlStyles[31].styles[0]":"Foreground=#c4a7e7","controlStyles[32].target":"StartDocked.AppListView#NavigationPanePlacesListView","controlStyles[32].styles[0]":"Margin=0,0,-38,0","controlStyles[33].target":"Windows.UI.Xaml.Controls.Border#AppBorder","controlStyles[33].styles[0]":"Background=#191724","controlStyles[33].styles[1]":"BorderThickness=1.5","controlStyles[33].styles[2]":"BorderBrush=#230752","controlStyles[33].styles[3]":"CornerRadius=25","controlStyles[34].target":"Windows.UI.Xaml.Controls.Grid#OuterBorderGrid","controlStyles[34].styles[0]":"CornerRadius=25","controlStyles[35].target":"Windows.UI.Xaml.Controls.Border#TaskbarSearchBackground","controlStyles[35].styles[0]":"BorderThickness=1.5","controlStyles[35].styles[1]":"BorderBrush=#230752","controlStyles[36].target":"StartDocked.LauncherFrame > Grid#RootGrid > Grid#RootContent","controlStyles[36].styles[0]":"MaxWidth=500","controlStyles[36].styles[1]":"Width=500","controlStyles[36].styles[2]":"MinWidth=500","controlStyles[37].target":"StartDocked.StartSizingFramePanel","controlStyles[37].styles[0]":"MaxWidth=500","controlStyles[37].styles[1]":"Width=500","controlStyles[37].styles[2]":"MinWidth=500","controlStyles[38].target":"StartDocked.LauncherFrame > Grid#RootGrid > Grid#RootContent","controlStyles[38].styles[0]":"MaxWidth=500","controlStyles[38].styles[1]":"Width=500","controlStyles[38].styles[2]":"MinWidth=500","controlStyles[39].target":"StartDocked.StartSizingFrame","controlStyles[39].styles[0]":"MinWidth=500","controlStyles[39].styles[1]":"Width=500","controlStyles[39].styles[2]":"MaxWidth=500","controlStyles[40].target":"StartMenu:ExpandedFolderList","controlStyles[40].styles[0]":"Margin=-50,0,-50,0"}

**Comment by bbmaster123** [comment]
Thanks!

I've taken a look and there doesn't seem to be any issues with your styles, and search is being styled correctly on my end:

![Image](https://github.com/user-attachments/assets/d3d65df2-b304-498c-b822-3b04b1046422)

what exactly isn't working? I don't see any _Search menu WebView styles_, so none of the search CONTENT is being styled, according to the code above. Is there something specific you're trying to achieve in the search menu?

**Comment by NearRaindrop116** [comment]
@bbmaster123 
nothing specific, it just doesnt work at all. is it possibly because im using  the portable version?

**Comment by NearRaindrop116** [comment]
@bbmaster123 Its been a bit, i thought it might have been fixed in the recent update but no. do you have any other ideas on how i could fix it or if it could have been any other apps that might have messed with something?

**Comment by bbmaster123** [comment]
@NearRaindrop116 

unfortunately I'm not sure what the issue is for sure, and the log doesn't tell me very much. It might be helpful though to see what the log says if you disable and re enable the mod. I can see at least it's hooking searchhost.exe which is good.

you can maybe also try this WIP rosepine which I'm adapting for an upcoming update to the start menu, hopefully it works but if not make sure you have your most recent code saved elsewhere so you can go back

```
{
  "controlStyles[0].target": "Windows.UI.Xaml.Controls.Grid#UndockedRoot",
  "controlStyles[0].styles[0]": "Width=350",
  "controlStyles[0].styles[1]": "Margin=0,-40,0,0",
  "controlStyles[1].target": "Windows.UI.Xaml.Controls.Grid#AllAppsRoot",
  "controlStyles[1].styles[0]": "Width=320",
  "controlStyles[1].styles[1]": "Transform3D:=<CompositeTransform3D TranslateX=\"-800\" />",
  "controlStyles[1].styles[2]": "Margin=-30,-60,0,0",
  "controlStyles[2].target": "Windows.UI.Xaml.Controls.Grid#ShowMoreSuggestions",
  "controlStyles[2].styles[0]": "Visibility=Collapsed",
  "controlStyles[3].target": "Grid#TopLevelSuggestionsContainer",
  "controlStyles[3].styles[0]": "Visibility=Collapsed",
  "controlStyles[4].target": "Windows.UI.Xaml.Controls.Grid#TopLevelSuggestionsListHeader",
  "controlStyles[4].styles[0]": "Visibility=Collapsed",
  "controlStyles[5].target": "StartDocked.SearchBoxToggleButton",
  "controlStyles[5].styles[0]": "Margin=114,53,114,2",
  "controlStyles[5].styles[1]": "Background=#1f1d2e",
  "controlStyles[5].styles[2]": "BorderThickness=0",
  "controlStyles[6].target": "Windows.UI.Xaml.Controls.Grid#TopLevelRoot > Windows.UI.Xaml.Controls.Border",
  "controlStyles[6].styles[0]": "Visibility=Collapsed",
  "controlStyles[7].target": "Windows.UI.Xaml.Controls.Button#CloseAllAppsButton",
  "controlStyles[7].styles[0]": "Visibility=Collapsed",
  "controlStyles[8].target": "StartMenu.PinnedList",
  "controlStyles[8].styles[0]": "Height=340",
  "controlStyles[9].target": "StartDocked.NavigationPaneView#Margin",
  "controlStyles[9].styles[0]": "Margin=210,0,210,0",
  "controlStyles[10].target": "StartDocked.StartSizingFramePanel",
  "controlStyles[10].styles[0]": "BorderThickness=1.5",
  "controlStyles[10].styles[1]": "CornerRadius=25",
  "controlStyles[10].styles[2]": "BorderBrush=#ebbcba",
  "controlStyles[10].styles[3]": "Background=#191724",
  "controlStyles[11].target": "Windows.UI.Xaml.Controls.FontIcon > Windows.UI.Xaml.Controls.Grid > Windows.UI.Xaml.Controls.TextBlock",
  "controlStyles[11].styles[0]": "Foreground=#eb6f92",
  "controlStyles[12].target": "Windows.UI.Xaml.Controls.TextBlock#AppDisplayName",
  "controlStyles[12].styles[0]": "Foreground=#e0def4",
  "controlStyles[13].target": "Windows.UI.Xaml.Controls.TextBlock#DisplayName",
  "controlStyles[13].styles[0]": "Visibility=Collapsed",
  "controlStyles[14].target": "Windows.UI.Xaml.Controls.TextBlock#PinnedListHeaderText",
  "controlStyles[14].styles[0]": "Visibility=Collapsed",
  "controlStyles[15].target": "Windows.UI.Xaml.Controls.TextBlock#AllAppsHeading",
  "controlStyles[15].styles[0]": "Visibility=Collapsed",
  "controlStyles[16].target": "Windows.UI.Xaml.Controls.Grid#UserTileIcon",
  "controlStyles[16].styles[0]": "Visibility=Collapsed",
  "controlStyles[17].target": "StartMenu.PinnedListTile > Windows.UI.Xaml.Controls.Grid#Root",
  "controlStyles[17].styles[0]": "Padding=0,25,0,0",
  "controlStyles[18].target": "Windows.UI.Xaml.Controls.Grid#DroppedFlickerWorkaroundWrapper > Windows.UI.Xaml.Controls.Border#BackgroundBorder",
  "controlStyles[18].styles[0]": "BorderBrush=#191724",
  "controlStyles[18].styles[1]": "BorderThickness=5",
  "controlStyles[18].styles[2]": "Background=#1f1d2e",
  "controlStyles[18].styles[3]": "CornerRadius=20",
  "controlStyles[19].target": "StartDocked.PowerOptionsView",
  "controlStyles[19].styles[0]": "Margin=-335,-4,0,0",
  "controlStyles[20].target": "StartDocked.NavigationPaneButton#PowerButton > Windows.UI.Xaml.Controls.Grid > Windows.UI.Xaml.Controls.Border#BackgroundBorder",
  "controlStyles[20].styles[0]": "Background=#1f1d2e",
  "controlStyles[20].styles[1]": "CornerRadius=20",
  "controlStyles[21].target": "Windows.UI.Xaml.Controls.TextBlock[Text=]",
  "controlStyles[21].styles[0]": "Text=      ",
  "controlStyles[22].target": "StartDocked.NavigationPaneButton#PowerButton",
  "controlStyles[22].styles[0]": "Width=120",
  "controlStyles[23].target": "Windows.UI.Xaml.Controls.Grid#InnerContent > Windows.UI.Xaml.Shapes.Rectangle",
  "controlStyles[23].styles[0]": "Margin=150,53,134,0",
  "controlStyles[24].target": "Windows.UI.Xaml.Controls.TextBlock#PlaceholderText",
  "controlStyles[24].styles[0]": "Text=Search",
  "controlStyles[24].styles[1]": "Foreground=#524f67",
  "controlStyles[24].styles[2]": "FontFamily=JetBrainsMono NF",
  "controlStyles[25].target": "Windows.UI.Xaml.Controls.TextBlock[Text=]",
  "controlStyles[25].styles[0]": "Foreground=#c4a7e7",
  "controlStyles[26].target": "StartDocked.UserTileView",
  "controlStyles[26].styles[0]": "Visibility=Collapsed",
  "controlStyles[27].target": "Windows.UI.Xaml.Controls.Grid#ContentBorder > Windows.UI.Xaml.Controls.Border#BackgroundBorder",
  "controlStyles[27].styles[0]": "Background=#1f1d2e",
  "controlStyles[27].styles[1]": "CornerRadius=20",
  "controlStyles[28].target": "Windows.UI.Xaml.Controls.TextBlock[Text=]",
  "controlStyles[28].styles[0]": "Foreground=#c4a7e7",
  "controlStyles[29].target": "Windows.UI.Xaml.Controls.Border#AppBorder",
  "controlStyles[29].styles[0]": "Background=#191724",
  "controlStyles[29].styles[1]": "BorderThickness=1.5",
  "controlStyles[29].styles[2]": "BorderBrush=#ebbcba",
  "controlStyles[29].styles[3]": "CornerRadius=25",
  "controlStyles[30].target": "Windows.UI.Xaml.Controls.Grid#OuterBorderGrid",
  "controlStyles[30].styles[0]": "CornerRadius=25",
  "controlStyles[31].target": "Windows.UI.Xaml.Controls.Border#TaskbarSearchBackground",
  "controlStyles[31].styles[0]": "BorderThickness=1.5",
  "controlStyles[31].styles[1]": "BorderBrush=#ebbcba",
  "controlStyles[32].target": "StartDocked.LauncherFrame > Grid#RootGrid > Grid#RootContent",
  "controlStyles[32].styles[0]": "MaxWidth=500",
  "controlStyles[32].styles[1]": "Width=500",
  "controlStyles[32].styles[2]": "MinWidth=500",
  "controlStyles[33].target": "StartDocked.StartSizingFramePanel",
  "controlStyles[33].styles[0]": "MaxWidth=500",
  "controlStyles[33].styles[1]": "Width=500",
  "controlStyles[33].styles[2]": "MinWidth=500",
  "controlStyles[34].target": "StartDocked.LauncherFrame > Grid#RootGrid > Grid#RootContent",
  "controlStyles[34].styles[0]": "MaxWidth=500",
  "controlStyles[34].styles[1]": "Width=500",
  "controlStyles[34].styles[2]": "MinWidth=500",
  "controlStyles[35].target": "StartDocked.StartSizingFramePanel",
  "controlStyles[35].styles[0]": "MinWidth=500",
  "controlStyles[35].styles[1]": "Width=500",
  "controlStyles[35].styles[2]": "MaxWidth=500",
  "controlStyles[36].target": "StartMenu:ExpandedFolderList",
  "controlStyles[36].styles[0]": "Margin=-50,0,-50,0",
  "controlStyles[37].target": "Windows.UI.Xaml.Controls.Grid#MainContent",
  "controlStyles[37].styles[0]": "Margin=-112,-40,112,0",
  "controlStyles[37].styles[1]": "MaxWidth=500",
  "controlStyles[38].target": "Border#AcrylicBorder",
  "controlStyles[38].styles[0]": "Opacity=0",
  "controlStyles[10].styles[4]": "Height=500",
  "controlStyles[39].styles[0]": "Opacity=0",
  "controlStyles[39].target": "Border#AcrylicOverlay",
  "controlStyles[10].styles[5]": "CornerRadius=25",
  "controlStyles[22].styles[1]": "Margin=75,0,0,0",
  "controlStyles[8].styles[1]": "Margin=-2,0,0,0",
  "controlStyles[40].target": "StartDocked.StartSizingFramePanel",
  "controlStyles[40].styles[0]": "MinWidth=420",
  "controlStyles[40].styles[1]": "MaxWidth=420",
  "controlStyles[41].target": "MenuFlyoutPresenter",
  "controlStyles[41].styles[0]": "Background=#1f1d2e"
}
```

let me know how it goes!

**Comment by NearRaindrop116** [comment]
@bbmaster123 I noticed that its just styling the search bar of the search menu which i previously did not notice because the color was to similar to the BG, is it possible this is what it was styling in the debug log instead of the entire thing?

![Image](https://github.com/user-attachments/assets/646bbca4-a7f4-4628-a0a1-839fd2523f59)

**Comment by NearRaindrop116** [comment]
> I don't see any _Search menu WebView styles_, so none of the search CONTENT is being styled, according to the code above.

Wait, is the content this bit?

![Image](https://github.com/user-attachments/assets/35e58968-3362-4cd0-a131-6e047d571d9f)

cause if so, i was trying to do that the entire time.

**Comment by bbmaster123** [comment]
its definitely styling the search box

and yes that is the content area, but you should still be able to set the background and border colors, as in my earlier screenshot, which yours still doesn't fully match. Its just everything actually in the content area ie quick search, top apps, which can only be styled with web styles. Rosepine doesn't include web styles though, so really we're talking about getting the rest of your search page to match the border/background colors of search box at the top. 

have you tried using uwpspy? maybe somehow you can verify something using that, maybe a path is different for you for whatever reason, or something else?
Maybe you have high contrast mode turned on in windows settings? or maybe 
I'm not positive why its doing this, but I can see the colors aren't being applied correctly in your initial video

> cause if so, i was trying to do that the entire time.

Don't worry you weren't wasting your time trying to do something not possible or in any way incorrect!
Something is definitely not working as intended!

**Comment by NearRaindrop116** [comment]
@bbmaster123 this by chance?

![Image](https://github.com/user-attachments/assets/7a311571-e52d-4e0f-9f35-84a4ea04d908)

**Comment by NearRaindrop116** [comment]
@bbmaster123 Yeah that was it! Now everything looks the same! mostly, the bg is a bit brighter even though using the same color code but it doesn't really bother me enough to try and fix it.

Now everything matches, thank you for telling me about UWPSpy. Very helpful.

![Image](https://github.com/user-attachments/assets/efda7d24-522a-4eb3-b0ea-5913e0e785f1)

![Image](https://github.com/user-attachments/assets/7ec49a5e-c519-4bea-961a-1acd9c2709d7)

![Image](https://github.com/user-attachments/assets/4602453d-18c1-4dbc-aa5d-5071cdff867f)

![Image](https://github.com/user-attachments/assets/90560c99-7ef5-4559-863e-ea17a4f5bab6)

![Image](https://github.com/user-attachments/assets/9bb6d552-11af-41ef-85a5-66751e5fdcab)

![Image](https://github.com/user-attachments/assets/0db83820-f19c-4040-8ca8-2a0c34b71d03)

**Comment by bbmaster123** [comment]
@NearRaindrop116 ah yes that looks much better! I'm glad you found the correct target, I'm not sure why it was a different target for you, possibly microsoft A/B testing features again for all I know!

Regarding the color being a bit lighter, I would suggest double check there isn't another almost transparent background layer on top of the custom color, if there is it would lighten its appearance. Its possible, even likely that since one of your targets was different, another is also different.

let me know if you need anything else :)

**Comment by NearRaindrop116** [comment]
Actually I do have one more question, what is the one for the system tray? i cant seem to find it anywhere

**Comment by NearRaindrop116** [comment]
@bbmaster123 Thanks, ill try that!
