### ISSUE TITLE
When using new start menu layout, the power button menu, click those options no responsive

### ISSUE THREAD

**Issue by chuck00000** [ramensoftware/windows-11-start-menu-styling-guide#244]
<img width="340" height="330" alt="Image" src="https://github.com/user-attachments/assets/41f749e2-aef0-4228-8ab5-a9d56fc1a7a9" />

**Comment by bbmaster123** [comment]
please try the WIP version of that theme [https://github.com/bbmaster123/FWFU/blob/main/WIP%20-%20updated%20start%20menu%20themes%202025%20(new%20start%20menu).json](https://github.com/bbmaster123/FWFU/blob/main/WIP%20-%20updated%20start%20menu%20themes%202025%20(new%20start%20menu).json)

it should be fixed in every WIP theme, but also, if you notice any other bugs please do let me know so I can fix them asap

**Comment by chuck00000** [comment]
<img width="1920" height="1024" alt="Image" src="https://github.com/user-attachments/assets/473ebf63-ee4d-46cf-81d9-ef0c92bf5168" />

I copied that .json, still not working

**Comment by bbmaster123** [comment]
@chuck00000 please set your theme to None in the dropdown, right now you're using a mix of the old code and new code
